import { Node, mergeAttributes } from '@tiptap/core';
import { ReactNodeViewRenderer } from '@tiptap/react';
import { NodeSelection } from '@tiptap/pm/state';
import ImageView from '../nodeViews/ImageView';

// ============================================================================
// Image — Tiptap block atom node mirroring the schema's ImageBlock.
// ----------------------------------------------------------------------------
// group 'block' + atom (no editable content). Draggable/selectable so it
// reorders like any other block and clicking it sets a NodeSelection that the
// ImagePopoverHost watches to open the edit popover.
//
// Attrs (round-trip via the rendered figure/img DOM, so copy-paste within the
// editor survives):
//   - id:      stable block id (data-block-id), regenerated by serialize anyway.
//   - src:     image URL ('' = unset placeholder; dropped by serialize).
//   - alt:     accessibility text (schema requires it; defaults to '').
//   - caption: optional figcaption text.
//
// In-editor look is the compact placeholder card (ImageView), NOT the actual
// <figure><img>. The real image only renders in the published/print output
// (the renderer package's renderImage), which already exists — this node's
// renderHTML matches that shape only so editor clipboard round-trips cleanly.
//
// Popover: a single root-level ImagePopoverHost (mirrors BlankPopoverHost) —
// never a per-node mounted popover, per the standing reconciliation constraint.
// ============================================================================

declare module '@tiptap/core' {
    interface Commands<ReturnType> {
        image: {
            // Insert an image block and select it so the edit popover opens.
            // Empty attrs ⇒ a placeholder card prompting for a source.
            insertImage: (attrs?: {
                src?: string;
                alt?: string;
                caption?: string;
            }) => ReturnType;
            // Update a selected image's attrs. preserveSelection (default true)
            // re-asserts the NodeSelection after setNodeMarkup so the popover
            // stays open through edits; close-time flush passes false.
            updateImageAttrs: (
                pos: number,
                attrs: Partial<{ src: string; alt: string; caption: string }>,
                options?: { preserveSelection?: boolean },
            ) => ReturnType;
        };
    }
}

export const Image = Node.create({
    name: 'image',
    group: 'block',
    atom: true,
    draggable: true,
    selectable: true,

    addAttributes() {
        return {
            id: {
                default: '',
                parseHTML: (element) =>
                    element.getAttribute('data-block-id') ?? '',
                renderHTML: (attributes) =>
                    attributes.id ? { 'data-block-id': attributes.id } : {},
            },
            // src/alt/caption live on the rendered img/figcaption, not as
            // attributes on the figure, so renderHTML returns {} for them and
            // the node's renderHTML below emits the actual elements.
            src: {
                default: '',
                parseHTML: (element) =>
                    element.querySelector('img')?.getAttribute('src') ?? '',
                renderHTML: () => ({}),
            },
            alt: {
                default: '',
                parseHTML: (element) =>
                    element.querySelector('img')?.getAttribute('alt') ?? '',
                renderHTML: () => ({}),
            },
            caption: {
                default: '',
                parseHTML: (element) =>
                    element.querySelector('figcaption')?.textContent ?? '',
                renderHTML: () => ({}),
            },
        };
    },

    parseHTML() {
        return [{ tag: 'figure[data-block-type="image"]' }];
    },

    renderHTML({ node, HTMLAttributes }) {
        const src = (node.attrs.src as string) ?? '';
        const alt = (node.attrs.alt as string) ?? '';
        const caption = (node.attrs.caption as string) ?? '';
        const children: Array<
            [string, Record<string, unknown>] | [string, Record<string, unknown>, string]
        > = [
            [
                'img',
                { src, alt, loading: 'lazy', decoding: 'async' },
            ],
        ];
        if (caption) children.push(['figcaption', {}, caption]);
        return [
            'figure',
            mergeAttributes(
                { 'data-block-type': 'image', class: 'block-image' },
                HTMLAttributes,
            ),
            ...children,
        ];
    },

    addNodeView() {
        return ReactNodeViewRenderer(ImageView);
    },

    addCommands() {
        return {
            insertImage:
                (attrs = {}) =>
                ({ state, dispatch, tr }) => {
                    const type = state.schema.nodes.image;
                    if (!type) return false;
                    const node = type.create({
                        id: crypto.randomUUID(),
                        src: attrs.src ?? '',
                        alt: attrs.alt ?? '',
                        caption: attrs.caption ?? '',
                    });
                    if (dispatch) {
                        tr.replaceSelectionWith(node);
                        // After replaceSelectionWith the selection lands just
                        // after the inserted leaf; its start is selection.from -
                        // nodeSize. Re-select it as a NodeSelection so the
                        // popover opens immediately. Falls back silently to the
                        // default selection if the position doesn't resolve.
                        const insertedPos = tr.selection.from - node.nodeSize;
                        if (insertedPos >= 0) {
                            const candidate = tr.doc.nodeAt(insertedPos);
                            if (candidate && candidate.type === type) {
                                try {
                                    tr.setSelection(
                                        NodeSelection.create(tr.doc, insertedPos),
                                    );
                                } catch {
                                    /* defensive — non-fatal */
                                }
                            }
                        }
                        dispatch(tr.scrollIntoView());
                    }
                    return true;
                },

            updateImageAttrs:
                (pos, attrs, options) =>
                ({ tr, state, dispatch }) => {
                    const node = state.doc.nodeAt(pos);
                    if (!node || node.type.name !== 'image') {
                        return false;
                    }
                    const nextAttrs = { ...node.attrs, ...attrs };
                    if (dispatch) {
                        tr.setNodeMarkup(pos, undefined, nextAttrs);
                        const preserveSelection =
                            options?.preserveSelection ?? true;
                        if (preserveSelection) {
                            try {
                                tr.setSelection(
                                    NodeSelection.create(tr.doc, pos),
                                );
                            } catch {
                                /* defensive — non-fatal */
                            }
                        }
                    }
                    return true;
                },
        };
    },
});
