import { Node, mergeAttributes } from '@tiptap/core';
import { ReactNodeViewRenderer } from '@tiptap/react';
import { NodeSelection } from '@tiptap/pm/state';
import ImageView from '../nodeViews/ImageView';

// ============================================================================
// Image — Tiptap block atom node mirroring the schema's ImageBlock.
// ----------------------------------------------------------------------------
// group 'block' + atom (no editable content). Draggable/selectable so it
// reorders like any other block and clicking it sets a NodeSelection that the
// ImagePopoverHost watches to open the edit popover.
//
// Attrs (round-trip via the rendered figure/img DOM, so copy-paste within the
// editor survives):
//   - id:      stable block id (data-block-id), regenerated by serialize anyway.
//   - src:     image URL ('' = unset placeholder; dropped by serialize).
//   - alt:     accessibility text (schema requires it; defaults to '').
//   - caption: optional figcaption text.
//   - width:   sizing fraction of container width in (0, 1]; null = full width.
//   - align:   'left' | 'right'; null = center (the default). Mirrors the
//              schema's sizing fragment; no UI sets these yet (Drop 3 adds
//              corner drag-handles) — carried so imported docs round-trip.
//
// In-editor look is the compact placeholder card (ImageView), NOT the actual
// <figure><img>. The real image only renders in the published/print output
// (the renderer package's renderImage), which already exists — this node's
// renderHTML matches that shape only so editor clipboard round-trips cleanly.
//
// Popover: a single root-level ImagePopoverHost (mirrors BlankPopoverHost) —
// never a per-node mounted popover, per the standing reconciliation constraint.
// ============================================================================

declare module '@tiptap/core' {
    interface Commands<ReturnType> {
        image: {
            // Insert an image block and select it so the edit popover opens.
            // Empty attrs ⇒ a placeholder card prompting for a source.
            insertImage: (attrs?: {
                src?: string;
                alt?: string;
                caption?: string;
            }) => ReturnType;
            // Update a selected image's attrs. preserveSelection (default true)
            // re-asserts the NodeSelection after setNodeMarkup so the popover
            // stays open through edits; close-time flush passes false.
            updateImageAttrs: (
                pos: number,
                attrs: Partial<{
                    src: string;
                    alt: string;
                    caption: string;
                    width: number | null;
                    align: 'left' | 'right' | null;
                    crop: { x: number; y: number; w: number; h: number } | null;
                    srcAspect: number | null;
                }>,
                options?: { preserveSelection?: boolean },
            ) => ReturnType;
            // Remove the image block at pos. Releasing the NodeSelection lets
            // ImagePopoverHost close the edit popover on its own.
            deleteImage: (pos: number) => ReturnType;
        };
    }
}

// Transaction-meta signal: the command bar's Replace primary asks
// ImagePopoverHost to open the source popover (it no longer auto-opens on
// selection). A transient meta (read in the host's transaction listener) — no
// persisted plugin state needed. (Alt/caption moved to the Advanced drawer, so
// there is nothing to focus but the URL field, which the popover does itself.)
export const OPEN_IMAGE_POPOVER = 'openImagePopover';

export const Image = Node.create({
    name: 'image',
    group: 'block',
    atom: true,
    draggable: true,
    selectable: true,

    addAttributes() {
        return {
            id: {
                default: '',
                parseHTML: (element) =>
                    element.getAttribute('data-block-id') ?? '',
                renderHTML: (attributes) =>
                    attributes.id ? { 'data-block-id': attributes.id } : {},
            },
            // src/alt/caption live on the rendered img/figcaption, not as
            // attributes on the figure, so renderHTML returns {} for them and
            // the node's renderHTML below emits the actual elements.
            src: {
                default: '',
                parseHTML: (element) =>
                    element.querySelector('img')?.getAttribute('src') ?? '',
                renderHTML: () => ({}),
            },
            alt: {
                default: '',
                parseHTML: (element) =>
                    element.querySelector('img')?.getAttribute('alt') ?? '',
                renderHTML: () => ({}),
            },
            caption: {
                default: '',
                parseHTML: (element) =>
                    element.querySelector('figcaption')?.textContent ?? '',
                renderHTML: () => ({}),
            },
            // Sizing attrs live as data attributes on the figure itself so
            // editor copy-paste round-trips them. Same names the renderer
            // emits (data-block-align) / consumes, minus the CSS plumbing.
            width: {
                default: null as number | null,
                parseHTML: (element) => {
                    const raw = element.getAttribute('data-block-width');
                    if (raw === null) return null;
                    const n = Number(raw);
                    return Number.isFinite(n) && n > 0 && n <= 1 ? n : null;
                },
                renderHTML: (attributes) =>
                    typeof attributes.width === 'number'
                        ? { 'data-block-width': String(attributes.width) }
                        : {},
            },
            align: {
                default: null as 'left' | 'right' | null,
                parseHTML: (element) => {
                    const raw = element.getAttribute('data-block-align');
                    return raw === 'left' || raw === 'right' ? raw : null;
                },
                renderHTML: (attributes) =>
                    attributes.align === 'left' || attributes.align === 'right'
                        ? { 'data-block-align': attributes.align }
                        : {},
            },
            // Crop window (schema ImageBlock.crop) — the visible sub-rectangle,
            // JSON on data-crop for clipboard round-trip; storage goes through
            // serialize.ts. Stored with srcAspect (both-or-neither).
            crop: {
                default: null as { x: number; y: number; w: number; h: number } | null,
                parseHTML: (element) => {
                    const raw = element.getAttribute('data-crop');
                    if (!raw) return null;
                    try {
                        const c = JSON.parse(raw) as Record<string, unknown>;
                        return typeof c?.x === 'number' &&
                            typeof c?.y === 'number' &&
                            typeof c?.w === 'number' &&
                            typeof c?.h === 'number'
                            ? { x: c.x, y: c.y, w: c.w, h: c.h }
                            : null;
                    } catch {
                        return null;
                    }
                },
                renderHTML: (attributes) =>
                    attributes.crop
                        ? { 'data-crop': JSON.stringify(attributes.crop) }
                        : {},
            },
            // The source's natural W/H ratio (schema ImageBlock.srcAspect), used
            // by the renderer to derive the crop pixel aspect. Positive.
            srcAspect: {
                default: null as number | null,
                parseHTML: (element) => {
                    const raw = element.getAttribute('data-src-aspect');
                    if (raw === null) return null;
                    const n = Number(raw);
                    return Number.isFinite(n) && n > 0 ? n : null;
                },
                renderHTML: (attributes) =>
                    typeof attributes.srcAspect === 'number'
                        ? { 'data-src-aspect': String(attributes.srcAspect) }
                        : {},
            },
        };
    },

    parseHTML() {
        return [{ tag: 'figure[data-block-type="image"]' }];
    },

    renderHTML({ node, HTMLAttributes }) {
        const src = (node.attrs.src as string) ?? '';
        const alt = (node.attrs.alt as string) ?? '';
        const caption = (node.attrs.caption as string) ?? '';
        const children: Array<
            [string, Record<string, unknown>] | [string, Record<string, unknown>, string]
        > = [
            [
                'img',
                { src, alt, loading: 'lazy', decoding: 'async' },
            ],
        ];
        if (caption) children.push(['figcaption', {}, caption]);
        return [
            'figure',
            mergeAttributes(
                { 'data-block-type': 'image', class: 'block-image' },
                HTMLAttributes,
            ),
            ...children,
        ];
    },

    addNodeView() {
        return ReactNodeViewRenderer(ImageView);
    },

    addCommands() {
        return {
            insertImage:
                (attrs = {}) =>
                ({ state, dispatch, tr }) => {
                    const type = state.schema.nodes.image;
                    if (!type) return false;
                    const node = type.create({
                        id: crypto.randomUUID(),
                        src: attrs.src ?? '',
                        alt: attrs.alt ?? '',
                        caption: attrs.caption ?? '',
                    });
                    if (dispatch) {
                        tr.replaceSelectionWith(node);
                        // After replaceSelectionWith the selection lands just
                        // after the inserted leaf; its start is selection.from -
                        // nodeSize. Re-select it as a NodeSelection so the
                        // popover opens immediately. Falls back silently to the
                        // default selection if the position doesn't resolve.
                        const insertedPos = tr.selection.from - node.nodeSize;
                        if (insertedPos >= 0) {
                            const candidate = tr.doc.nodeAt(insertedPos);
                            if (candidate && candidate.type === type) {
                                try {
                                    tr.setSelection(
                                        NodeSelection.create(tr.doc, insertedPos),
                                    );
                                } catch {
                                    /* defensive — non-fatal */
                                }
                            }
                        }
                        // A freshly inserted image has no source — open the edit
                        // popover straight onto the URL field (the host no longer
                        // auto-opens on plain selection, so the insert must ask).
                        tr.setMeta(OPEN_IMAGE_POPOVER, true);
                        dispatch(tr.scrollIntoView());
                    }
                    return true;
                },

            updateImageAttrs:
                (pos, attrs, options) =>
                ({ tr, state, dispatch }) => {
                    const node = state.doc.nodeAt(pos);
                    if (!node || node.type.name !== 'image') {
                        return false;
                    }
                    const nextAttrs = { ...node.attrs, ...attrs };
                    // CR-INV2: replacing the source invalidates any crop (a crop
                    // into image X is meaningless for image Y) and its captured
                    // srcAspect. Clear BOTH whenever src changes to a different
                    // value, unless the same patch sets crop explicitly (the
                    // crop editor never changes src, so the two never collide).
                    if (
                        typeof attrs.src === 'string' &&
                        attrs.src !== node.attrs.src &&
                        !('crop' in attrs)
                    ) {
                        nextAttrs.crop = null;
                        nextAttrs.srcAspect = null;
                    }
                    if (dispatch) {
                        tr.setNodeMarkup(pos, undefined, nextAttrs);
                        const preserveSelection =
                            options?.preserveSelection ?? true;
                        if (preserveSelection) {
                            try {
                                tr.setSelection(
                                    NodeSelection.create(tr.doc, pos),
                                );
                            } catch {
                                /* defensive — non-fatal */
                            }
                        }
                    }
                    return true;
                },

            deleteImage:
                (pos) =>
                ({ tr, state, dispatch }) => {
                    const node = state.doc.nodeAt(pos);
                    if (!node || node.type.name !== 'image') {
                        return false;
                    }
                    if (dispatch) {
                        tr.delete(pos, pos + node.nodeSize);
                    }
                    return true;
                },
        };
    },
});
