/**
 * @vitest-environment jsdom
 */
// =============================================================================
// init.test.ts — JSDOM-backed tests for the init pass
// -----------------------------------------------------------------------------
// First JSDOM test file in the runtime suite. The strategies.test.ts pure-
// function tests don't need a DOM; this file does (init walks document).
// The @vitest-environment docblock above switches just this file's
// environment without affecting strategies.test.ts (which stays in the
// default 'node' environment).
//
// Pattern: build a minimal HTML fragment that mirrors what the renderer
// emits for the case under test, install it into JSDOM's document.body,
// run init() / buildRefs() / parseConfig(), assert the refs maps and state
// are populated correctly.
//
// The HTML fragments are hand-written rather than generated by calling
// renderActivity(), because the goal is to test init.ts in isolation
// against the data-attribute contract. A renderer regression would surface
// here as a mismatch between hand-written fixture and renderer output —
// caught by the broader render.test.ts suite.
// =============================================================================

import { describe, it, expect, beforeEach } from 'vitest';
import { init, buildRefs } from '../init.js';
import { parseConfig } from '../config.js';
import { createInitialState } from '../state.js';

function setupDOM(html: string): void {
    document.body.innerHTML = html;
}

const SAMPLE_CONFIG = {
    activityId: '11111111-1111-1111-1111-111111111111',
    versionNum: 1,
    submissionEndpoint: 'https://example.com/submit',
    submissionMode: 'free',
    revisionMode: 'free',
    gradingMode: 'auto',
};

function configScript(config: Record<string, unknown> = SAMPLE_CONFIG): string {
    return (
        '<script id="activity-config" type="application/json">' +
        JSON.stringify(config) +
        '</script>'
    );
}

beforeEach(() => {
    document.body.innerHTML = '';
});

describe('parseConfig', () => {
    it('parses a valid activity-config script tag', () => {
        setupDOM(configScript());
        const config = parseConfig();
        expect(config).not.toBeNull();
        expect(config!.activityId).toBe('11111111-1111-1111-1111-111111111111');
        expect(config!.submissionMode).toBe('free');
        expect(config!.revisionMode).toBe('free');
        expect(config!.gradingMode).toBe('auto');
    });

    it('returns null when the script tag is absent', () => {
        setupDOM('<p>no config here</p>');
        expect(parseConfig()).toBeNull();
    });

    it('returns null when JSON is malformed', () => {
        setupDOM(
            '<script id="activity-config" type="application/json">not json</script>',
        );
        expect(parseConfig()).toBeNull();
    });

    it('returns null when a required field is missing', () => {
        // Defensive parsing — a renderer regression that drops a field should
        // fall back to no-op runtime, not propagate undefined into the call sites.
        const incomplete: Record<string, unknown> = { ...SAMPLE_CONFIG };
        delete incomplete.activityId;
        setupDOM(configScript(incomplete));
        expect(parseConfig()).toBeNull();
    });

    it("preserves an explicit answerFeedback of 'on_check'", () => {
        setupDOM(configScript({ ...SAMPLE_CONFIG, answerFeedback: 'on_check' }));
        expect(parseConfig()!.answerFeedback).toBe('on_check');
    });

    it("preserves an explicit answerFeedback of 'immediate'", () => {
        setupDOM(configScript({ ...SAMPLE_CONFIG, answerFeedback: 'immediate' }));
        expect(parseConfig()!.answerFeedback).toBe('immediate');
    });

    it("coerces a MISSING answerFeedback to 'immediate' (pre-field back-compat)", () => {
        // Pages published before the field existed had no answerFeedback and
        // self-checked on blur. They must keep that behavior, so missing → immediate.
        setupDOM(configScript()); // SAMPLE_CONFIG has no answerFeedback
        expect(parseConfig()!.answerFeedback).toBe('immediate');
    });

    it("coerces an invalid answerFeedback to 'immediate'", () => {
        setupDOM(configScript({ ...SAMPLE_CONFIG, answerFeedback: 'bogus' }));
        expect(parseConfig()!.answerFeedback).toBe('immediate');
    });
});

describe('buildRefs — sections', () => {
    it('builds a section ref for each .activity-section', () => {
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1"' +
            ' data-is-checkpoint="true"></section>' +
            '<section class="activity-section" data-section-id="sec-2"' +
            ' data-is-checkpoint="false"></section>',
        );
        const refs = buildRefs();
        expect(refs.sections.size).toBe(2);
        expect(refs.sections.get('sec-1')?.isCheckpoint).toBe(true);
        expect(refs.sections.get('sec-2')?.isCheckpoint).toBe(false);
    });

    it('treats absent data-is-checkpoint as not-a-checkpoint (single mode)', () => {
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1"></section>',
        );
        const refs = buildRefs();
        expect(refs.sections.get('sec-1')?.isCheckpoint).toBe(false);
    });

    it('captures checkpoint button + score slot when present', () => {
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1"' +
            ' data-is-checkpoint="true">' +
            '<button class="js-checkpoint-btn" data-for-section="sec-1"' +
            ' type="button">Check this section</button>' +
            '<div class="js-section-score" data-for-section="sec-1" hidden></div>' +
            '</section>',
        );
        const refs = buildRefs();
        const sec = refs.sections.get('sec-1');
        expect(sec?.checkButton).not.toBeNull();
        expect(sec?.scoreEl).not.toBeNull();
    });

    it('leaves checkButton + scoreEl null on non-checkpoint sections', () => {
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1"' +
            ' data-is-checkpoint="false"></section>',
        );
        const refs = buildRefs();
        const sec = refs.sections.get('sec-1');
        expect(sec?.checkButton).toBeNull();
        expect(sec?.scoreEl).toBeNull();
    });
});

describe('buildRefs — fill-in-blank blocks', () => {
    it('builds a fill_in_blank ref with parsed data attributes', () => {
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1">' +
            '<div class="block block-fill-in-blank"' +
            ' data-block-category="question"' +
            ' data-block-type="fill_in_blank"' +
            ' data-block-id="block-1"' +
            ' data-solution="Combine like terms."' +
            ' data-has-confidence-rating="true"' +
            ' data-skills="[&quot;skill-a&quot;]">' +
            '<div class="block-problem-body">' +
            '<div class="js-solution" data-for-block="block-1" hidden>' +
            'Combine like terms.</div>' +
            '<fieldset class="js-confidence-rating" data-for-block="block-1">' +
            '<legend>How confident are you?</legend></fieldset>' +
            '</div></div></section>',
        );
        const refs = buildRefs();
        const block = refs.fillInBlanks.get('block-1');
        expect(block).toBeDefined();
        expect(block?.solution).toBe('Combine like terms.');
        expect(block?.solutionEl).not.toBeNull();
        expect(block?.hasConfidenceRating).toBe(true);
        expect(block?.confidenceFieldset).not.toBeNull();
        expect(block?.skills).toEqual(['skill-a']);
        expect(block?.sectionId).toBe('sec-1');
    });

    it('leaves solution/confidence fields at defaults when attributes are absent', () => {
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1">' +
            '<div class="block block-fill-in-blank"' +
            ' data-block-type="fill_in_blank" data-block-id="block-1">' +
            '<div class="block-problem-body"></div></div></section>',
        );
        const refs = buildRefs();
        const block = refs.fillInBlanks.get('block-1');
        expect(block?.solution).toBeNull();
        expect(block?.solutionEl).toBeNull();
        expect(block?.hasConfidenceRating).toBe(false);
        expect(block?.confidenceFieldset).toBeNull();
        expect(block?.skills).toEqual([]);
    });
});

describe('buildRefs — blanks', () => {
    it('builds a blank ref with wrapper, feedback, and parsed data', () => {
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1">' +
            '<div class="block block-fill-in-blank"' +
            ' data-block-type="fill_in_blank" data-block-id="block-1">' +
            '<div class="block-problem-body">' +
            '<span class="blank-wrapper">' +
            '<input type="text" class="blank" data-blank-id="blank-1"' +
            ' data-blank-answers="x+1|x + 1"' +
            ' data-hint="Try factoring."' +
            ' data-mistake-feedback="[{&quot;match&quot;:&quot;2x&quot;,' +
            '&quot;feedback&quot;:&quot;Did you forget the constant?&quot;}]" />' +
            '<button class="js-blank-hint" type="button"></button>' +
            '<span class="js-blank-feedback" data-for-blank="blank-1"' +
            ' aria-live="polite" hidden></span>' +
            '</span></div></div></section>',
        );
        const refs = buildRefs();
        const blank = refs.blanks.get('blank-1');
        expect(blank).toBeDefined();
        expect(blank?.answers).toEqual(['x+1', 'x + 1']);
        expect(blank?.strategy).toBe('list');
        expect(blank?.hint).toBe('Try factoring.');
        expect(blank?.mistakeFeedback).toEqual([
            { match: '2x', feedback: 'Did you forget the constant?' },
        ]);
        expect(blank?.feedbackEl).not.toBeNull();
        expect(blank?.hintButton).not.toBeNull();
        expect(blank?.blockId).toBe('block-1');
        expect(blank?.sectionId).toBe('sec-1');
    });

    it('leaves hint affordances null when blank has no hint', () => {
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1">' +
            '<div class="block block-fill-in-blank"' +
            ' data-block-type="fill_in_blank" data-block-id="block-1">' +
            '<div class="block-problem-body">' +
            '<span class="blank-wrapper">' +
            '<input type="text" class="blank" data-blank-id="blank-1"' +
            ' data-blank-answers="x" />' +
            '<span class="js-blank-feedback" data-for-blank="blank-1"' +
            ' aria-live="polite" hidden></span>' +
            '</span></div></div></section>',
        );
        const refs = buildRefs();
        const blank = refs.blanks.get('blank-1');
        expect(blank?.hint).toBeNull();
        expect(blank?.hintButton).toBeNull();
        expect(blank?.mistakeFeedback).toEqual([]);
    });

    it('cross-references blockIds and blankIds correctly', () => {
        // A section with one block containing two blanks. Section.blankIds
        // collects all of them; block.blankIds collects this block's; each
        // blank's blockId/sectionId points back up.
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1">' +
            '<div class="block block-fill-in-blank"' +
            ' data-block-type="fill_in_blank" data-block-id="block-1">' +
            '<div class="block-problem-body">' +
            '<span class="blank-wrapper">' +
            '<input class="blank" data-blank-id="b1" data-blank-answers="1" />' +
            '<span class="js-blank-feedback" data-for-blank="b1" aria-live="polite" hidden></span>' +
            '</span>' +
            '<span class="blank-wrapper">' +
            '<input class="blank" data-blank-id="b2" data-blank-answers="2" />' +
            '<span class="js-blank-feedback" data-for-blank="b2" aria-live="polite" hidden></span>' +
            '</span>' +
            '</div></div></section>',
        );
        const refs = buildRefs();
        expect(refs.sections.get('sec-1')?.blankIds).toEqual(['b1', 'b2']);
        expect(refs.sections.get('sec-1')?.blockIds).toEqual(['block-1']);
        expect(refs.fillInBlanks.get('block-1')?.blankIds).toEqual(['b1', 'b2']);
        expect(refs.blanks.get('b1')?.blockId).toBe('block-1');
        expect(refs.blanks.get('b2')?.sectionId).toBe('sec-1');
    });
});

describe('buildRefs — hint modal', () => {
    const MODAL_HTML =
        '<div class="js-hint-modal" id="hint-modal" role="dialog" hidden>' +
        '<div class="js-hint-modal-dialog" role="document">' +
        '<button class="js-hint-modal-close" type="button"></button>' +
        '<div class="js-hint-modal-body"></div>' +
        '</div></div>';

    it('builds a HintModalRef when complete markup is present', () => {
        setupDOM(configScript() + MODAL_HTML);
        const refs = buildRefs();
        expect(refs.hintModal).not.toBeNull();
        expect(refs.hintModal?.overlay.classList.contains('js-hint-modal')).toBe(
            true,
        );
        expect(refs.hintModal?.dialog).not.toBeNull();
        expect(refs.hintModal?.bodyEl).not.toBeNull();
        expect(refs.hintModal?.closeButton).not.toBeNull();
    });

    it('returns null hintModal when no modal markup is present', () => {
        setupDOM(configScript());
        const refs = buildRefs();
        expect(refs.hintModal).toBeNull();
    });

    it('returns null hintModal when markup is incomplete (all-or-nothing)', () => {
        setupDOM(
            configScript() +
            '<div class="js-hint-modal"><div class="js-hint-modal-dialog">' +
            '</div></div>',
        );
        const refs = buildRefs();
        expect(refs.hintModal).toBeNull();
    });
});

describe('createInitialState', () => {
    it('produces a SectionState entry for every section in refs', () => {
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1"></section>' +
            '<section class="activity-section" data-section-id="sec-2"></section>',
        );
        const refs = buildRefs();
        const state = createInitialState(refs);
        expect(Object.keys(state.sections).sort()).toEqual(['sec-1', 'sec-2']);
        expect(state.sections['sec-1']?.checked).toBe(false);
        expect(state.sections['sec-1']?.locked).toBe(false);
        expect(state.sections['sec-1']?.score).toBe(0);
        expect(state.sections['sec-1']?.total).toBe(0);
        expect(state.sections['sec-1']?.checkedAt).toBeNull();
    });

    it('starts submitted=false, attemptNumber=1, studentName empty', () => {
        setupDOM(configScript());
        const refs = buildRefs();
        const state = createInitialState(refs);
        expect(state.submitted).toBe(false);
        expect(state.attemptNumber).toBe(1);
        expect(state.studentName).toBe('');
    });
});

describe('init — orchestrator', () => {
    it('returns config + refs + state when everything is well-formed', () => {
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1"' +
            ' data-is-checkpoint="false"></section>',
        );
        const result = init();
        expect(result).not.toBeNull();
        expect(result!.config.activityId).toBe('11111111-1111-1111-1111-111111111111');
        expect(result!.refs.sections.size).toBe(1);
        expect(result!.state.submitted).toBe(false);
        expect(result!.state.sections['sec-1']?.checked).toBe(false);
    });

    it('returns null when config is missing (caller falls back to no-op)', () => {
        setupDOM(
            '<section class="activity-section" data-section-id="sec-1"></section>',
        );
        expect(init()).toBeNull();
    });
});
