/**
 * @vitest-environment jsdom
 */
// =============================================================================
// init.test.ts — JSDOM-backed tests for the init pass
// -----------------------------------------------------------------------------
// First JSDOM test file in the runtime suite. The strategies.test.ts pure-
// function tests don't need a DOM; this file does (init walks document).
// The @vitest-environment docblock above switches just this file's
// environment without affecting strategies.test.ts (which stays in the
// default 'node' environment).
//
// Pattern: build a minimal HTML fragment that mirrors what the renderer
// emits for the case under test, install it into JSDOM's document.body,
// run init() / buildRefs() / parseConfig(), assert the refs maps and state
// are populated correctly.
//
// The HTML fragments are hand-written rather than generated by calling
// renderActivity(), because the goal is to test init.ts in isolation
// against the data-attribute contract. A renderer regression would surface
// here as a mismatch between hand-written fixture and renderer output —
// caught by the broader render.test.ts suite.
// =============================================================================

import { describe, it, expect, beforeEach } from 'vitest';
import { init, buildRefs } from '../init.js';
import { parseConfig } from '../config.js';
import { createInitialState } from '../state.js';

function setupDOM(html: string): void {
    document.body.innerHTML = html;
}

const SAMPLE_CONFIG = {
    activityId: '11111111-1111-1111-1111-111111111111',
    versionNum: 1,
    submissionEndpoint: 'https://example.com/submit',
    submissionMode: 'free',
    revisionMode: 'free',
    gradingMode: 'auto',
};

function configScript(config: Record<string, unknown> = SAMPLE_CONFIG): string {
    return (
        '<script id="activity-config" type="application/json">' +
        JSON.stringify(config) +
        '</script>'
    );
}

beforeEach(() => {
    document.body.innerHTML = '';
});

describe('parseConfig', () => {
    it('parses a valid activity-config script tag', () => {
        setupDOM(configScript());
        const config = parseConfig();
        expect(config).not.toBeNull();
        expect(config!.activityId).toBe('11111111-1111-1111-1111-111111111111');
        expect(config!.submissionMode).toBe('free');
        expect(config!.revisionMode).toBe('free');
        expect(config!.gradingMode).toBe('auto');
    });

    it('returns null when the script tag is absent', () => {
        setupDOM('<p>no config here</p>');
        expect(parseConfig()).toBeNull();
    });

    it('returns null when JSON is malformed', () => {
        setupDOM(
            '<script id="activity-config" type="application/json">not json</script>',
        );
        expect(parseConfig()).toBeNull();
    });

    it('returns null when a required field is missing', () => {
        // Defensive parsing — a renderer regression that drops a field should
        // fall back to no-op runtime, not propagate undefined into the call sites.
        const incomplete: Record<string, unknown> = { ...SAMPLE_CONFIG };
        delete incomplete.activityId;
        setupDOM(configScript(incomplete));
        expect(parseConfig()).toBeNull();
    });

    it("preserves an explicit answerFeedback of 'on_check'", () => {
        setupDOM(configScript({ ...SAMPLE_CONFIG, answerFeedback: 'on_check' }));
        expect(parseConfig()!.answerFeedback).toBe('on_check');
    });

    it("preserves an explicit answerFeedback of 'immediate'", () => {
        setupDOM(configScript({ ...SAMPLE_CONFIG, answerFeedback: 'immediate' }));
        expect(parseConfig()!.answerFeedback).toBe('immediate');
    });

    it("coerces a MISSING answerFeedback to 'immediate' (pre-field back-compat)", () => {
        // Pages published before the field existed had no answerFeedback and
        // self-checked on blur. They must keep that behavior, so missing → immediate.
        setupDOM(configScript()); // SAMPLE_CONFIG has no answerFeedback
        expect(parseConfig()!.answerFeedback).toBe('immediate');
    });

    it("coerces an invalid answerFeedback to 'immediate'", () => {
        setupDOM(configScript({ ...SAMPLE_CONFIG, answerFeedback: 'bogus' }));
        expect(parseConfig()!.answerFeedback).toBe('immediate');
    });
});

describe('buildRefs — sections', () => {
    it('builds a section ref for each .activity-section', () => {
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1"' +
            ' data-is-checkpoint="true"></section>' +
            '<section class="activity-section" data-section-id="sec-2"' +
            ' data-is-checkpoint="false"></section>',
        );
        const refs = buildRefs();
        expect(refs.sections.size).toBe(2);
        expect(refs.sections.get('sec-1')?.isCheckpoint).toBe(true);
        expect(refs.sections.get('sec-2')?.isCheckpoint).toBe(false);
    });

    it('treats absent data-is-checkpoint as not-a-checkpoint (single mode)', () => {
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1"></section>',
        );
        const refs = buildRefs();
        expect(refs.sections.get('sec-1')?.isCheckpoint).toBe(false);
    });

    it('captures checkpoint button + score slot when present', () => {
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1"' +
            ' data-is-checkpoint="true">' +
            '<button class="js-checkpoint-btn" data-for-section="sec-1"' +
            ' type="button">Check this section</button>' +
            '<div class="js-section-score" data-for-section="sec-1" hidden></div>' +
            '</section>',
        );
        const refs = buildRefs();
        const sec = refs.sections.get('sec-1');
        expect(sec?.checkButton).not.toBeNull();
        expect(sec?.scoreEl).not.toBeNull();
    });

    it('leaves checkButton + scoreEl null on non-checkpoint sections', () => {
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1"' +
            ' data-is-checkpoint="false"></section>',
        );
        const refs = buildRefs();
        const sec = refs.sections.get('sec-1');
        expect(sec?.checkButton).toBeNull();
        expect(sec?.scoreEl).toBeNull();
    });
});

describe('buildRefs — fill-in-blank blocks', () => {
    it('builds a fill_in_blank ref with parsed data attributes', () => {
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1">' +
            '<div class="block block-fill-in-blank"' +
            ' data-block-category="question"' +
            ' data-block-type="fill_in_blank"' +
            ' data-block-id="block-1"' +
            ' data-has-confidence-rating="true"' +
            ' data-skills="[&quot;skill-a&quot;]">' +
            '<div class="block-problem-body">' +
            '<div class="js-solution" data-for-block="block-1" hidden>' +
            'Combine like terms.</div>' +
            '<fieldset class="js-confidence-rating" data-for-block="block-1">' +
            '<legend>How confident are you?</legend></fieldset>' +
            '</div></div></section>',
        );
        const refs = buildRefs();
        const block = refs.fillInBlanks.get('block-1');
        expect(block).toBeDefined();
        expect(block?.solutionEl).not.toBeNull();
        expect(block?.hasConfidenceRating).toBe(true);
        expect(block?.confidenceFieldset).not.toBeNull();
        expect(block?.skills).toEqual(['skill-a']);
        expect(block?.sectionId).toBe('sec-1');
    });

    it('leaves solution/confidence fields at defaults when attributes are absent', () => {
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1">' +
            '<div class="block block-fill-in-blank"' +
            ' data-block-type="fill_in_blank" data-block-id="block-1">' +
            '<div class="block-problem-body"></div></div></section>',
        );
        const refs = buildRefs();
        const block = refs.fillInBlanks.get('block-1');
        expect(block?.solutionEl).toBeNull();
        expect(block?.hasConfidenceRating).toBe(false);
        expect(block?.confidenceFieldset).toBeNull();
        expect(block?.skills).toEqual([]);
    });
});

describe('buildRefs — display (static) graphs', () => {
    it('collects a display graph into graphDisplays, not graphs, and never scores it', () => {
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1">' +
            '<div class="block block-interactive-graph block-graph-display"' +
            ' data-block-category="content"' +
            ' data-block-type="interactive_graph"' +
            ' data-block-id="disp-1"' +
            ' data-graph-block-id="disp-1"' +
            ' data-graph-interaction-type="display"' +
            ' data-graph-config="{&quot;xMin&quot;:-5,&quot;xMax&quot;:5,&quot;yMin&quot;:-5,&quot;yMax&quot;:5}"' +
            ' data-graph-drawables="[{&quot;kind&quot;:&quot;point&quot;,&quot;at&quot;:[1,2]}]"' +
            ' data-graph-kit-src="https://cdn.example.com/graph-kit-ABC.js">' +
            '<div class="block-problem-body">' +
            '<div class="graph-canvas" data-graph-canvas="disp-1" role="img"></div>' +
            '</div></div></section>',
        );
        const refs = buildRefs();
        // In the display map, with the element + kit src (config/drawables are
        // parsed KIT-side from the element since the bundle-budget move).
        const disp = refs.graphDisplays.get('disp-1');
        expect(disp).toBeDefined();
        expect(disp?.kitSrc).toContain('graph-kit-ABC.js');
        expect(disp?.el.dataset.graphDrawables).toContain('point');
        expect(disp?.canvas.dataset.graphCanvas).toBe('disp-1');
        // NOT in the graded graphs map, and NOT in the section's scored ids.
        expect(refs.graphs.has('disp-1')).toBe(false);
        expect(refs.sections.get('sec-1')?.graphBlockIds).toEqual([]);
    });

    it('keeps graded and display graphs in the same section separate', () => {
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1">' +
            '<div class="block block-interactive-graph"' +
            ' data-block-type="interactive_graph" data-block-id="graded-1"' +
            ' data-graph-block-id="graded-1"' +
            ' data-graph-interaction-type="plot_point"' +
            ' data-graph-config="{}" data-graph-answer-key="{}">' +
            '<div class="graph-canvas" data-graph-canvas="graded-1" role="application" tabindex="0"></div>' +
            '</div>' +
            '<div class="block block-interactive-graph block-graph-display"' +
            ' data-block-type="interactive_graph" data-block-id="disp-1"' +
            ' data-graph-block-id="disp-1"' +
            ' data-graph-interaction-type="display"' +
            ' data-graph-config="{}" data-graph-drawables="[]">' +
            '<div class="graph-canvas" data-graph-canvas="disp-1" role="img"></div>' +
            '</div></section>',
        );
        const refs = buildRefs();
        expect(refs.graphs.has('graded-1')).toBe(true);
        expect(refs.graphDisplays.has('disp-1')).toBe(true);
        expect(refs.sections.get('sec-1')?.graphBlockIds).toEqual(['graded-1']);
    });
});

describe('buildRefs — blanks', () => {
    it('builds a blank ref with wrapper, affordances, and parsed data', () => {
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1">' +
            '<div class="block block-fill-in-blank"' +
            ' data-block-type="fill_in_blank" data-block-id="block-1">' +
            '<div class="block-problem-body">' +
            '<span class="blank-wrapper">' +
            '<input type="text" class="blank" data-blank-id="blank-1"' +
            ' data-blank-answers="x+1|x + 1" />' +
            '<button class="js-blank-hint" type="button"></button>' +
            '<button class="js-blank-mistake" type="button" hidden></button>' +
            '<template class="js-blank-hint-content">Try <strong>factoring</strong>.</template>' +
            '<template class="js-blank-mistake-content" data-match="2x">' +
            'Did you forget the constant?</template>' +
            '</span></div></div></section>',
        );
        const refs = buildRefs();
        const blank = refs.blanks.get('blank-1');
        expect(blank).toBeDefined();
        expect(blank?.answers).toEqual(['x+1', 'x + 1']);
        expect(blank?.strategy).toBe('list');
        // hintContent is the <template> element; its rich markup is preserved.
        expect(blank?.hintContent).not.toBeNull();
        expect(blank?.hintContent?.innerHTML).toBe('Try <strong>factoring</strong>.');
        expect(blank?.mistakeFeedback).toHaveLength(1);
        expect(blank?.mistakeFeedback[0]?.match).toBe('2x');
        expect(blank?.mistakeFeedback[0]?.content.innerHTML).toBe(
            'Did you forget the constant?',
        );
        expect(blank?.hintButton).not.toBeNull();
        expect(blank?.mistakeButton).not.toBeNull();
        expect(blank?.blockId).toBe('block-1');
        expect(blank?.sectionId).toBe('sec-1');
        // No data-blank-group on this input → ungrouped.
        expect(blank?.groupId).toBeNull();
    });

    it('reads data-blank-group into BlankRef.groupId for grouped blanks', () => {
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1">' +
            '<div class="block block-fill-in-blank"' +
            ' data-block-type="fill_in_blank" data-block-id="block-1">' +
            '<div class="block-problem-body">' +
            '<span class="blank-wrapper">' +
            '<input type="text" class="blank blank-grouped" data-blank-id="blank-1"' +
            ' data-blank-answers="2" data-blank-group="blank-1" />' +
            '</span>' +
            '<span class="blank-wrapper">' +
            '<input type="text" class="blank blank-grouped" data-blank-id="blank-2"' +
            ' data-blank-answers="3" data-blank-group="blank-1" />' +
            '</span></div></div></section>',
        );
        const refs = buildRefs();
        // Both members carry the same group id (the anchor blank's id).
        expect(refs.blanks.get('blank-1')?.groupId).toBe('blank-1');
        expect(refs.blanks.get('blank-2')?.groupId).toBe('blank-1');
    });

    it('leaves affordances null when blank has neither hint nor mistakes', () => {
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1">' +
            '<div class="block block-fill-in-blank"' +
            ' data-block-type="fill_in_blank" data-block-id="block-1">' +
            '<div class="block-problem-body">' +
            '<span class="blank-wrapper">' +
            '<input type="text" class="blank" data-blank-id="blank-1"' +
            ' data-blank-answers="x" />' +
            '</span></div></div></section>',
        );
        const refs = buildRefs();
        const blank = refs.blanks.get('blank-1');
        expect(blank?.hintContent).toBeNull();
        expect(blank?.hintButton).toBeNull();
        expect(blank?.mistakeButton).toBeNull();
        expect(blank?.mistakeFeedback).toEqual([]);
    });

    it('cross-references blockIds and blankIds correctly', () => {
        // A section with one block containing two blanks. Section.blankIds
        // collects all of them; block.blankIds collects this block's; each
        // blank's blockId/sectionId points back up.
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1">' +
            '<div class="block block-fill-in-blank"' +
            ' data-block-type="fill_in_blank" data-block-id="block-1">' +
            '<div class="block-problem-body">' +
            '<span class="blank-wrapper">' +
            '<input class="blank" data-blank-id="b1" data-blank-answers="1" />' +
            '</span>' +
            '<span class="blank-wrapper">' +
            '<input class="blank" data-blank-id="b2" data-blank-answers="2" />' +
            '</span>' +
            '</div></div></section>',
        );
        const refs = buildRefs();
        expect(refs.sections.get('sec-1')?.blankIds).toEqual(['b1', 'b2']);
        expect(refs.sections.get('sec-1')?.blockIds).toEqual(['block-1']);
        expect(refs.fillInBlanks.get('block-1')?.blankIds).toEqual(['b1', 'b2']);
        expect(refs.blanks.get('b1')?.blockId).toBe('block-1');
        expect(refs.blanks.get('b2')?.sectionId).toBe('sec-1');
    });
});

describe('buildRefs — popover', () => {
    const POPOVER_HTML =
        '<div class="js-popover" id="activity-popover" role="dialog" hidden>' +
        '<div class="js-popover-header">' +
        '<h2 class="js-popover-title" id="popover-title"></h2>' +
        '<button class="js-popover-close" type="button"></button>' +
        '</div>' +
        '<div class="js-popover-body"></div>' +
        '</div>';

    it('builds a PopoverRef when complete markup is present', () => {
        setupDOM(configScript() + POPOVER_HTML);
        const refs = buildRefs();
        expect(refs.popover).not.toBeNull();
        expect(refs.popover?.el.classList.contains('js-popover')).toBe(true);
        expect(refs.popover?.header).not.toBeNull();
        expect(refs.popover?.titleEl).not.toBeNull();
        expect(refs.popover?.bodyEl).not.toBeNull();
        expect(refs.popover?.closeButton).not.toBeNull();
    });

    it('returns null popover when no popover markup is present', () => {
        setupDOM(configScript());
        const refs = buildRefs();
        expect(refs.popover).toBeNull();
    });

    it('returns null popover when markup is incomplete (all-or-nothing)', () => {
        setupDOM(
            configScript() +
            '<div class="js-popover"><div class="js-popover-header">' +
            '</div></div>',
        );
        const refs = buildRefs();
        expect(refs.popover).toBeNull();
    });
});

describe('createInitialState', () => {
    it('produces a SectionState entry for every section in refs', () => {
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1"></section>' +
            '<section class="activity-section" data-section-id="sec-2"></section>',
        );
        const refs = buildRefs();
        const state = createInitialState(refs);
        expect(Object.keys(state.sections).sort()).toEqual(['sec-1', 'sec-2']);
        expect(state.sections['sec-1']?.checked).toBe(false);
        expect(state.sections['sec-1']?.locked).toBe(false);
        expect(state.sections['sec-1']?.score).toBe(0);
        expect(state.sections['sec-1']?.total).toBe(0);
        expect(state.sections['sec-1']?.checkedAt).toBeNull();
    });

    it('starts submitted=false, attemptNumber=1, studentName empty', () => {
        setupDOM(configScript());
        const refs = buildRefs();
        const state = createInitialState(refs);
        expect(state.submitted).toBe(false);
        expect(state.attemptNumber).toBe(1);
        expect(state.studentName).toBe('');
    });

    // A section with one fill-in-blank block holding two blanks — the fixture
    // exercises both keyed sub-stores at once.
    const TWO_BLANK_DOM =
        configScript() +
        '<section class="activity-section" data-section-id="sec-1">' +
        '<div class="block block-fill-in-blank"' +
        ' data-block-type="fill_in_blank" data-block-id="block-1">' +
        '<div class="block-problem-body">' +
        '<span class="blank-wrapper">' +
        '<input class="blank" data-blank-id="b1" data-blank-answers="1" />' +
        '</span>' +
        '<span class="blank-wrapper">' +
        '<input class="blank" data-blank-id="b2" data-blank-answers="2" />' +
        '</span>' +
        '</div></div></section>';

    it('produces a defaulted BlankState entry for every blank in refs', () => {
        setupDOM(TWO_BLANK_DOM);
        const state = createInitialState(buildRefs());
        // One entry per blank, keyed by blank.id — and nothing extra.
        expect(Object.keys(state.blanks).sort()).toEqual(['b1', 'b2']);
        for (const id of ['b1', 'b2']) {
            expect(state.blanks[id]?.result).toBeNull();
            expect(state.blanks[id]?.matchedMistake).toBeNull();
        }
    });

    it('produces a defaulted BlockState entry for every fill_in_blank block', () => {
        setupDOM(TWO_BLANK_DOM);
        const state = createInitialState(buildRefs());
        // Keyed by block.id (from refs.fillInBlanks) — two blanks, one block.
        expect(Object.keys(state.blocks)).toEqual(['block-1']);
        expect(state.blocks['block-1']?.solutionRevealed).toBe(false);
        expect(state.blocks['block-1']?.confidence).toBeNull();
    });

    it('leaves blanks and blocks empty when the page has none', () => {
        // A section with no fill-in-blank blocks → both keyed sub-stores empty.
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1"></section>',
        );
        const state = createInitialState(buildRefs());
        expect(state.blanks).toEqual({});
        expect(state.blocks).toEqual({});
    });
});

describe('init — orchestrator', () => {
    it('returns config + refs + state when everything is well-formed', () => {
        setupDOM(
            configScript() +
            '<section class="activity-section" data-section-id="sec-1"' +
            ' data-is-checkpoint="false"></section>',
        );
        const result = init();
        expect(result).not.toBeNull();
        expect(result!.config.activityId).toBe('11111111-1111-1111-1111-111111111111');
        expect(result!.refs.sections.size).toBe(1);
        expect(result!.state.submitted).toBe(false);
        expect(result!.state.sections['sec-1']?.checked).toBe(false);
    });

    it('returns null when config is missing (caller falls back to no-op)', () => {
        setupDOM(
            '<section class="activity-section" data-section-id="sec-1"></section>',
        );
        expect(init()).toBeNull();
    });
});
