// =============================================================================
// markdownImportPrompt.ts — the canonical "format for the importer" instruction
// -----------------------------------------------------------------------------
// A self-contained prompt block a teacher can paste into ChatGPT/Claude so the
// model emits Markdown that the activity importer (markdownToTiptap) accepts.
// The Import dialog's "Copy AI prompt" button copies this verbatim.
//
// This is the human-facing twin of the rules encoded in markdownToTiptap.ts and
// documented in docs/markdown-import-format.md — keep all three in sync when the
// accepted syntax changes. LaTeX backslashes are doubled because these are
// single-quoted strings (so `\\frac` is the literal `\frac`).
// =============================================================================

export const MARKDOWN_IMPORT_AI_PROMPT = [
    'You are writing a classroom activity that I will import by pasting Markdown.',
    'Put your ENTIRE reply inside a single fenced code block — begin and end it',
    'with a line of three backtick characters — and write nothing outside it. That',
    'makes this chat show a Copy button, so I get the raw Markdown instead of a',
    'rendered preview. Inside that block, follow these rules exactly.',
    '',
    'STRUCTURE',
    '- Headings use #, ##, ### (three levels only).',
    '- Put a blank line between every block. Each problem must be its own',
    '  paragraph separated by a blank line — lines that touch merge into one block.',
    '- To start a new checkpoint section, end a heading with {checkpoint}:',
    '  ## Part 2 {checkpoint}',
    '',
    'FILL-IN-THE-BLANK',
    '- Wrap each answer in double curly braces:  The capital of France is {{Paris}}.',
    '- Offer alternate accepted answers with vertical bars:  made of hydrogen and {{oxygen|O2}}.',
    '- When two blanks may be answered in either order (e.g. factoring), mark the',
    '  second one with a leading tilde:  (x + {{2}})(x + {{~3}}). Each answer still',
    '  counts once, so 2 and 3 in either order is right but 2 and 2 is not.',
    '- Always put a real answer inside the braces (an empty {{}} is ignored).',
    '- For a NUMERIC answer, put = right after the braces:  the area is {{=12}}.',
    '  Numeric blanks accept every equivalent form — 0.5, 1/2, .50, and 1,234',
    '  all count — so prefer them for any purely numeric answer. Add a tolerance',
    '  with +- at the end:  pi is about {{=3.14 +- 0.01}}. Combine with the',
    '  tilde as {{~=3}}.',
    '- For a MATH answer graded by expression equivalence (2a, a+a and a*2 all',
    '  count as equal), use two equals signs:  simplify to {{==2a}}. Combine with',
    '  the tilde as {{~==2a}}.',
    '- Add an optional HINT a student can open when stuck by starting a bar-segment',
    '  with ?:  {{Paris | ?It starts with P}}. One hint per blank.',
    '- Give targeted feedback for a specific wrong answer with a bar-segment written',
    '  !wrong :: message (repeatable):',
    '    {{Paris | !Lyon :: That is the third-largest city, not the capital}}',
    '- Inside the braces the order is: the answer, then any mix of |alternate',
    '  answers, one ?hint, and !wrong :: feedback pairs. Hint and feedback text',
    '  cannot contain |, {, or }. For an accepted answer that itself starts with',
    '  ? or !, double the mark:  {{a | ??x}} also accepts the literal "?x".',
    '- Blanks work only in normal paragraphs and list items — never inside a heading.',
    '- A numbered or bulleted list whose items each contain a blank becomes one',
    '  problem per item — a clean way to write a problem set.',
    '',
    'MATH (write real LaTeX)',
    '- Inline math between single dollar signs:  the area is $\\frac{1}{2}bh$',
    '- A displayed equation on its own line, with a blank line above and below:',
    '',
    '  $$\\int_0^1 x\\,dx = \\frac{1}{2}$$',
    '',
    '- A gradeable GAP inside an equation — \\gap{answer} — lets the student fill in',
    '  the missing part (ideal for a faded example\'s "complete the step"):',
    '    $$2x = \\gap{8}$$   then   $$x = \\gap{4}$$',
    '  The answer is graded by math equivalence, so 8, 8.0, and 4+4 all count.',
    '',
    'DEFINITIONS (a tappable vocabulary term with a pop-up explanation)',
    '- Wrap a term and its meaning in double square brackets, split by ::',
    '    The [[mitochondria :: the powerhouse of the cell]] makes energy.',
    '- The term stays in the sentence; the definition shows in a pop-up (it may',
    '  include $inline$ math). Term and definition can’t contain square brackets;',
    '  a [[bracketed phrase]] with no :: stays literal text.',
    '',
    'GRAPHS (a fenced block with the `graph` tag becomes a coordinate-plane question)',
    '- ```graph … ``` with one statement per line:',
    '    axes: -10..10, -10..10        (optional; this is the default window)',
    '    prompt: Graph the inequality.',
    '    answer: y > 2x + 1',
    '    options: partial-credit, allow-no-solution',
    '- The answer line takes ANY equation format (y = 2x + 3, 2x + 3y = 6,',
    '  y - 5 = 2(x - 1), x^2 - 4, x = 4), an inequality (the <, <=, >, >= sign',
    '  sets the dotted/solid boundary and the shaded side), a point list like',
    '  (2, 3), (4, 5), a ray or segment like ray (1, 2) through (3, 4) open or',
    '  segment (1, 2) to (3, 4) (open/closed set each endpoint style, default',
    '  closed), a region like region (0,0), (4,0), (2,4), or the word none for',
    '  a "cannot be graphed" trick question. Supported answer curves: linear,',
    '  quadratic, exponential, logarithmic, and vertical lines.',
    '- The prompt line may include inline math: prompt: Graph $y = 2x + 3$.',
    '- Optional targeted feedback for an anticipated wrong answer (repeatable):',
    '    mistake: y = x + 2 :: Remember - the number multiplying x is the slope.',
    '    mistake: (4, 3) :: Coordinates are (x, y) - x comes first.',
    '    mistake: segment (1, 2) to (3, 4) :: Think about whether the graph should stop or keep going.',
    '- options: (comma-separated) turn on grading behaviours:',
    '    partial-credit        score a multi-part answer per object (no effect on a single-object answer)',
    '    allow-no-solution     give the student a "no solution" choice',
    '    no-solution-correct   make "no solution" THE correct answer and any drawn answer a decoy (a trick question)',
    '    no-builtin-feedback   turn OFF the automatic mistake hints (swapped coordinates, swapped slope/intercept, …), which are on by default',
    '- For an ungraded figure, use show: lines instead of an answer:',
    '    show: point (2, 3) closed "A"',
    '    show: line y = x dashed      (dotted works too)',
    '    show: line y > 2x + 1 for x >= 0   (inequalities shade; domains clip)',
    '    show: expression sin(x)      (plots any formula)',
    '    show: ray (0,0) (2,1) open',
    '',
    'NUMBER LINES (a fenced block with the `numberline` tag becomes a 1-D number-line question)',
    '- ```numberline … ``` with one statement per line:',
    '    prompt: Graph $x \\ge -2$.',
    '    answer: x >= -2',
    '- answer: is EITHER a point (or comma-separated points) the student plots —',
    '  answer: -3, 4 — OR an inequality the student graphs as an interval/ray:',
    '    answer: x >= 3        (a ray from 3 to the right, closed dot)',
    '    answer: x < 5         (a ray to the left, open dot)',
    '    answer: -2 <= x < 5   (a bounded interval)',
    '  >= and <= draw a closed (filled) endpoint; > and < draw an open one.',
    '- axis: -10..10 step 2 (optional) sets the window and tick step; left out,',
    '  the axis fits the answer automatically.',
    '- Optional lines:  solution: <worked explanation>   and   options: confidence',
    '',
    'DATA PLOTS (a fenced block with the `dataplot` tag becomes a statistics-chart question)',
    '- ```dataplot … ``` with one statement per line:',
    '    prompt: Make a dot plot of the data.',
    '    data: 3, 5, 5, 6, 8',
    '    answer: dotplot',
    '- data: lists the dataset (commas or spaces; repeat the line to continue a',
    '  long dataset). The correct chart is COMPUTED from the data — never try',
    '  to describe the chart itself.',
    '- answer: dotplot, histogram, or boxplot makes a graded build (the student',
    '  constructs that chart of the data). Use show: instead of answer: for a',
    '  static ungraded chart the student just reads:  show: boxplot',
    '- axis: 0..20 step 5 (optional) sets the number-line window and tick step;',
    '  left out, the axis fits the data automatically. For a histogram the step',
    '  is also the bar (bin) width.',
    '- A boxplot answer may add how close each of the five handles must be:',
    '  answer: boxplot tolerance 1   (default 0.5).',
    '- Optional lines:  solution: <worked explanation>   and   options: confidence',
    '',
    'MULTIPLE CHOICE (a fenced block with the `mc` tag becomes a multiple-choice question)',
    '- ```mc … ``` with one statement per line:',
    '    prompt: What is $2 + 2$?',
    '    ( ) 3 :: Check your addition.',
    '    (x) 4',
    '    ( ) 22',
    '- Mark the correct choice with (x); a plain ( ) is a wrong choice. Use',
    '  square brackets [x] / [ ] instead for a "select all that apply" question',
    '  (marking more than one (x) also makes it multi-select automatically).',
    '- Optional feedback after :: on any choice is shown to a student who picks it.',
    '- Optional lines:  solution: <worked explanation>   and   options: confidence',
    '- Choice text and the prompt may include $inline$ math.',
    '- A choice may carry an image, shown below its text:  (x) ![a square](https://…)',
    '  — the choice text may be the image alone.',
    '- A choice can be a static graph instead of text — "which graph shows…":',
    '    (x) graph: line y = 2x   (uses the show: forms: point/line/curve/segment/ray/region)',
    '',
    'MATCHING (a fenced block with the `match` tag becomes a matching question)',
    '- ```match … ``` with one pair per line, written item = correct option:',
    '    prompt: Match each equation to its slope.',
    '    y = 2x = 2',
    '    y = -x = -1',
    '    = 0',
    '- The LAST " = " on the line splits the pair, so equation items keep their',
    '  equals signs (write \\= for a literal equals, or use " -> " as the',
    '  separator instead:  y = 2x -> 2).',
    '- A line starting with = (or ->) adds an extra wrong option (a distractor).',
    '- Students see the options shuffled and lettered automatically — never write',
    '  the letters yourself.',
    '- Optional lines:  solution: <worked explanation>   and   options: confidence',
    '  (add options: reuse when several items share one option, e.g. classifying).',
    '- Either side may include $inline$ math or an image ![alt](https://…).',
    '- A side can be a static graph — "match the graph to its equation". Use -> as',
    '  the separator (the graph formula contains =):  graph: line y = 2x -> slope 2',
    '',
    'ORDERING (a fenced block with the `order` tag becomes a put-in-order question)',
    '- ```order … ``` with one item per line, LISTED IN THE CORRECT ORDER',
    '  (students see them shuffled and drag them back into sequence):',
    '    prompt: Put the steps for solving $2x + 3 = 11$ in order.',
    '    1. Subtract 3 from both sides',
    '    2. Divide both sides by 2',
    '    3. Check the solution',
    '- Leading numbers like "1." are optional decoration — the listed order is',
    '  what counts.',
    '- Optional lines:  solution: <worked explanation>   and   options: confidence',
    '',
    'LEARNING OBJECTIVES (a fenced block with the `objectives` tag becomes a goals list)',
    '- ```objectives … ``` with one objective per line:',
    '    title: Today\'s goals        (optional; defaults to "Learning objectives")',
    '    Solve two-step linear equations',
    '    Graph a line from its equation',
    '- A leading list marker (-, *, 1.) is fine — it is stripped. $inline$ math ok.',
    '',
    'WORKED EXAMPLE (a fenced block with the `worked` tag becomes a boxed example to study)',
    '- ```worked … ``` with an optional title: line, then one block per line:',
    '    title: Solving $2x + 3 = 11$   (optional)',
    '    Subtract 3 from both sides.',
    '    $$2x = 8$$',
    '    Divide by 2.',
    '    $$x = 4$$',
    '- Each line is its own block: a line that is only $$…$$ becomes a displayed',
    '  equation, every other line becomes a paragraph. Lists and images inside an',
    '  example are not supported here — add those in the editor.',
    '',
    'FADED WORKED EXAMPLE (a `faded` fenced block is a guided example the student completes)',
    '- ```faded … ``` is written just like ```worked, but any line containing a',
    '  {{blank}} becomes a step the STUDENT fills in:',
    '    title: Guided practice        (optional)',
    '    Subtract 3 from both sides.',
    '    $$2x = 8$$',
    '    x = {{4}}',
    '- Show the first steps, then fade (blank) the later ones. Blanks use the same',
    '  {{answer|alt}} / {{=numeric}} grammar as fill-in-the-blank.',
    '',
    'SELF-EXPLANATION (an `explain` fenced block is an ungraded free-text reflection)',
    '- ```explain … ``` — the prompt text, plus an optional sentence starter:',
    '    Why did you subtract 3 from both sides?',
    '    starter: I subtracted 3 because…',
    '- Ungraded: the student writes an answer for you to read; there is no key.',
    '',
    'SHORT ANSWER / ESSAY (a `shortanswer` or `essay` fence is a graded free-text question)',
    '- Both take a prompt line, an optional starter: placeholder, and an optional',
    '  grading rubric — one criterion per rubric: line, written',
    '  rubric: Label | points | optional note',
    '    ```shortanswer',
    '    prompt: Explain why the sum of two even numbers is even.',
    '    starter: The sum is even because…',
    '    rubric: Correct reasoning | 3 | Uses that an even number is 2k',
    '    rubric: Clear explanation | 2',
    '    ```',
    '- An essay adds a words: min-max length target (either side optional —',
    '  words: 200-300, words: 200-, words: -300); it shows the student a live',
    '  word counter:',
    '    ```essay',
    '    prompt: Argue whether zoos do more good than harm.',
    '    words: 200-300',
    '    rubric: Thesis | 3',
    '    rubric: Evidence | 5 | Cites at least two examples',
    '    ```',
    '- Both are teacher-graded against the rubric — there is no auto-scored key.',
    '  Use ```explain instead when the reflection should be ungraded.',
    '',
    'COLUMNS (a `columns` fence lays blocks out side by side)',
    '- ```columns … ``` with columns divided by a line that is only ---, then one',
    '  block per line inside each column:',
    '    Left column, first line',
    '    Left column, second line',
    '    ---',
    '    Right column',
    '- 2 to 6 columns. Each non-blank line is its own block: a $$…$$ line becomes a',
    '  displayed equation, a {{blank}} line becomes a fill-in-the-blank, every other',
    '  line becomes a paragraph. Keep column content simple (paragraphs, math,',
    '  blanks) — lists and headings inside a column are editor-only.',
    '',
    'CALLOUT (a `callout` fence is a tinted note box)',
    '- ```callout … ``` with an optional variant: line, then the note text:',
    '    variant: warning        (info | warning | success | note; default info)',
    '    Double-check your units before submitting.',
    '- The body is one line of text ($inline$ math ok); extra lines join together.',
    '',
    'OTHER',
    '- Bold **like this**, italic *like this*, inline code `like this`.',
    '- Images:  ![a short description](https://full-image-url)',
    '- Don\'t use tables, blockquotes, links, or any code block inside the activity',
    '  other than ```graph, ```numberline, ```dataplot, ```mc, ```match, ```order,',
    '  ```objectives, ```worked, ```faded, ```explain, ```shortanswer, ```essay,',
    '  ```columns, and ```callout — only the single outer block that wraps the whole',
    '  reply and those fences are allowed; anything unsupported imports as plain text.',
    '',
    'When I describe the activity I want, reply with only that single code block.',
].join('\n');
